felixge/node-dateformat

lib/dateformat.js

When requiring an AMD module, you're given the return value of that module definition. In this case, the return value of `dateFormat` was in fact the default format of the current date and time.
We instead should be passing an anonymous function to `define`, which in turn returns the `dateFormat` function.

Pass a function which returns the dateFormat function to AMD `define`

---

Readme.md

There's no need to mention standalone function in the Readme, because standalone is the only thing that exists now (`Date.prototype.format` was removed).

no need to mention standalone function any more

---

lib/dateformat.js
test/test_quotes.js

Their content was not ignored. Original [function](http://blog.stevenlevithan.com/archives/date-time-format) works correctly.
```js
// correct
dateFormat('2017-06-16', "'yyyy'") // yyyy
// wrong
dateFormat('2017-06-16', '"yyyy"') // "2017"
```

Fix incorrect work with double-quoted substrings.

---

package-lock.json

> It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs npm install in your package source to get the exact same dependency tree that you were developing on. Additionally, the diffs from these changes are human-readable and will inform you of any changes npm has made to your node_modules, so you can notice if any transitive dependencies were updated, hoisted, etc.
Source: [npm docs](https://docs.npmjs.com/cli/v6/configuring-npm/package-locks)
Closes #110

Add Package Lock

---

.npmignore
CONTRIBUTING.md
benchmark/benchmark.js
benchmark/previousDateFormat.js
package.json

Before making any changes to try and improve the performance of dateformat, I think we should implement a standardised measurement of benchmarking.  
This is to ensure that the changes really do improve performance, and to quantify the degree of improvement.  
This PR introduces a new Benchmarking Script that outputs the runtime and improvement for before and after the changes.  
It also introduces a small Contribution Guide which is just a place to add some documentation for the Benchmarking Script.
Here is an example of the output of the script, this is with no changes and shows just standard variance when running.  
closes: #117

Added a Performance Benchmarking Tool

---

benchmark/benchmark.js

The New column showed the old speeds and the Old column showed the new speeds.  
These were swapped and are now corrected.
closes #120

Fixed Issue with Benchmarking

---

.gitignore

Lib should only be generated when the app builds.
And so the contents of it should not be stored in source control.
closed #124

Remove lib From Source Control

---

.gitignore
src/dateformat.js

Currently when you run dateformat for a given mask, it goes through the process of calculating the result for every possible mask output.  
Then it filters it down to only use the ones it needs.  
This PR changes that functionality so that it only calculates for the masks that it needs.  
It does this by changing the variables to be functions, that way they only calculate when they are called.
This delivers significant performance improvements, particularly for masks that are very basic:
closes: #126

Performance Improvements.

---

package.json

The redundant polyfills dependency was removed to reduce the package size.
closes: #130

Remove Redundant Dependency

---

benchmark/previousDateFormat.js
src/dateformat.js

Most functions used the older `function` declarations.  
To standardise throughout the project, and to adopt a more modern syntax, this moves to using arrow functions for all functions.
closes: #133

Convert Functions to Using Arrow Functions

---

package.json
test/test_formats.js

Removed the Underscore Package from Dev Dependencies.
closes #137

Remove Redundant Dev Dependency

---

src/dateformat.js
test/test_mask-yyyy.js

Previously the yyyy mask would not pad the years before 1000.  
For example 0009 would display as 9.  
This changes this functionality so that it now always outputs as 4 long.  
It also ads some new tests for this functionality.
closes: #39

Apply Padding to yyyy Mask

---

src/dateformat.js

All variable declarations were done with `var`, instead they have been changed to use `const` and `let`.
closes: #135

Change Var to Const or Let

---

Readme.md
src/dateformat.js
test/test_formats.js

Previously there was an example mask format for all main formats other than the padding short format.  
Adding this mask type includes some useful utility, while also giving a good example of the padded format.
closes: #144

Added Padding Short Date Mask

---

src/dateformat.js
test/test_isoutcdatetime.js

Previously the date `1970-01-01` when when formatted would error and be set as the current date.  
This fixes that to keep the date that is passed through.
closes: #79

Fixed Invalid '1970-01-01' Formatting

---

package-lock.json
package.json

Previously the output of the package included the full code such as comments and variable names.  
Now, it uglifys the output to compress the size of it.  
This is so the package is smaller for users.
closes: #141

Uglify Output

---

src/dateformat.js
test/test_mask-l_.js

Format mask `L` is documented as `Milliseconds; gives 2 digits`.  
However, the previous implementation outputs 3 digits when millisecond is between 995-999.  
This is because we used `Math.round` which would round it up to `100`.  
This was fixed by instead using `Math.floor`.
closes: #146
closes: #89

Fix Rounding Issue with L Mask

---

Readme.md
benchmark/previousDateFormat.js
package-lock.json
src/dateformat.js
test/test_mask-o.js
test/test_mask-p.js

Because the feed validator for ATOM complains about timezone offset being given as `+0200` and not as `+02:00`, I added a slight modification of the `o` and called it `p` (like in PHP's date function).
I ended up killing my original pull request at https://github.com/felixge/node-dateformat/pull/56 (please close that) and building a completely new fix.
Cheers & thanks for this great lib,
Frank
closes: #148
closes: #81

Adding `p` as timezone offset, e.g. `+02:00`

---

Readme.md

Previously the `Z` Mask has an error where the description ended abruptly.  
This PR fixes that issue and continues the description.
closes: #74

:memo: Fix Issue with Z Mask Documentation

---

Readme.md
src/dateformat.js
test/test_mask-ww_.js

Creating a WW option which adds padding to weeks for weeks < 10

Adding padding to week (W)

---

src/dateformat.js

For https://github.com/felixge/node-dateformat/pull/104

Timezone abbrevs

---

src/dateformat.js
test/test_mask-z_.js

This PR aims to fix what both #104 and #165 attempted to do, this time with tests to ensure it works as expected and doesn't break in the future.
The gist is this:
The `Z` formatting option attempts to generate a nice timezone abbreviation by parsing the rendered date string, recognizing something like "Eastern Daylight Time" and changing that to `EDT`. For all unrecognized timezones (pretty much everything but common North American timezones) it would parse and display the `GMT+xxxx` offset from the date string instead.
This, however caused a couple of issues with Australian timezones. Because Australia has defined an "Australian Eastern Daylight Time" (for instance) it would erroneously match the same regex as the American "Eastern Daylight Time" and it would render as `EST` instead of …

Fix broken timezone abbreviations and GMT fallback

---

package.json

This adds the `.js` file extension to the value of the "main" field in `package.json`, which is required since this package uses ES modules. 
This fixes the deprecation warning: "Automatic extension resolution of the "main" field is deprecated for ES modules."
Fixes #175

Fix file extension in main field of package.json
